const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
const USER_POSTS_STATE_CHANGE = 'USER_POSTS_STATE_CHANGE'
const USER_FOLLOWING_STATE_CHANGE = 'USER_FOLLOWING_STATE_CHANGE'
const USERS_DATA_STATE_CHANGE = 'USERS_DATA_STATE_CHANGE'
const USERS_POSTS_STATE_CHANGE = 'USERS_POSTS_STATE_CHANGE';

export { USER_STATE_CHANGE, USER_FOLLOWING_STATE_CHANGE, USER_POSTS_STATE_CHANGE, USERS_DATA_STATE_CHANGE, USERS_POSTS_STATE_CHANGE }